#################### General settings ####################
# Device settings
use_gpu: True  # whether to use the gpu

# Inference simulation settings
sim_wall_time: 36  # unit: s. The simulation wall time. The simulation will stop if the wall time is reached.
sim_num: 2  # Number of simulations to run.

# Simulation metrics
save_collision_data_flag: True  # Save crash data. This must set to True if want to analyze crash type and crash severity.
gen_realistic_metric_flag: True  # Generate and save realistic metrics.
gen_realistic_metric_dict:  # What metrics to generate.
  PET: True  # Post-encroachment time.
  instant_speed: True  # Vehicle instantaneous speed
  yielding_speed_and_distance: True  # Each yielding moment calculate the yielding distance and speed with the conflicting vehicle.
  distance: True  # Vehicle distance

#################### Other settings ####################

# NeuralNDE model
# The parameters below are determined by your trained model
model: "transformer"
dataset: "ring"
history_length: 5  # number of historical steps input to the model
pred_length: 5  # number of predicted steps output by the model
m_tokens: 32  # maximum number of vehicles that can be handled by the model
# model_output: "position_xy"  # use traci.vehicle.moveToXY()
model_output: "position_dxdy"  # compute dx,dy, then use traci.vehicle.setSpeed()
# model_output: "no_set"  # not set traci, sumo log data
use_gt_prediction: False
# use_gt_prediction: True


# experiment_name: &experiment ring_position_close_loop_8-20
# Checkpoints of the trained models (behavior modeling net, safety mapping net, etc.)
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_behavior_net_training_0.4_no_jump2/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_1/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_speed_acc/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_xy_out/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_fixed_08-09-24/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_loop_8-20/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_moveToXY_8-26/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_moveToXY_angle_8-29/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_moveToXY_angle_arctan2_9-06/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_multi_configs_9-05/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_multiConf_libsumo_9-16/checkpoints/last_ckpt.pt"
behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_setSpeedMode_9-18/checkpoints/last_ckpt.pt" # good
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_setSpeedMode_9-18__refine_angle_9-22/checkpoints/last_ckpt.pt" # good
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_setSpeedMode_9-18__refine_angle_9-22_dxdy/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_setSpeedMode_9-18__refine_fix_angle_9-22/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_moveToXY_angle_9-24/checkpoints/last_ckpt.pt"
behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_test/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_pos_open_pred5_10-29_load_data/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_moveToXY_angleConvert_10-28/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_moveToXY_angleConvert_10-29/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_pos_open_dxdy_pred5_10-29/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_pos_open_dxdy_pred5_10-29_refined_pos_close_xy_11-3/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/0006_local_ring_pos_open_dataLoad_11-04/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/0007_local_0006__refine_pos_close_dxdy_setSpeed_11-04/checkpoints/last_ckpt.pt"
behavior_model_ckpt_dir: "./results/training/behavior_net/0007-2_local_0007__refine_pos_close_xy_moveToXY_cossin2deg_11-05/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/0008_pos_open_pred35_11-04/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/0009_pos_open_pred35_goals_11-04/checkpoints/last_ckpt.pt"
safety_mapper_ckpt_dir: "data/inference/rounD/safety_mapper_ckpt/safety_mapping_net.pt"

# Whether use neural safety mapping module
use_neural_safety_mapping: False

# Whether use conflict critic module (crash critic module)
use_conflict_critic_module: False

# Other inference simulation settings
sim_resol: 0.4  # simulation resolution. unit: s
rolling_step: 1  # How many pred steps to execute during autoregression.
interpolate_flag: False # Interpolate the trajectory to a finer time resolution for better visualization.
intep_steps: 3  # Number of steps to inter between steps. E.g., resolution is 0.4s intep_steps=3 then new resolution is 0.1s

# Simulation metrics dependencies
ROI_map_dir: "data/inference/ring/ROIs-map"  # Used for metric analysis.
PET_configs: # This is pixel coordinates of the basemap image
  width_start: 0
  width_end: 77
  width_n: 20
  width_res: 25.0
  height_start: 0
  height_end: 80
  height_n: 20
  height_res: 23.5
  # roundD drivable (936, 1678, 3)
  # width_start: 550
  # width_end: 1050
  # width_n: 20
  # width_res: 25.0
  # height_start: 230
  # height_end: 700
  # height_n: 20
  # height_res: 23.5

# Other save results and visualization
save_simulated_TIME_BUFF_flag: True  # Save all generated simulated trajectories
viz_flag: True  # Whether visualize the simulation.
save_viz_flag: True  # Save simulation visualizations
save_collision_data_flag: True
save_fps: 10

########## sumo ##############
gui: True
sumocfg_file_name: "./data/sumo/ring/circles.sumocfg"
# sumocfg_file_name: "./data/sumo/ring_24cars/circles.sumocfg"
# sumocfg_file_name: "./data/sumo/ring_18cars_0.1acc_1.5dec/circles.sumocfg"

# sumocfg_file_name: "./data/sumo/ring_18cars_0.7acc_0.7dec/circles.sumocfg"
# sumocfg_file_name: "./data/sumo/ring_18cars_80maxSpeed/circles.sumocfg"
max_steps: 1000 #1000
step_length: 0.4
