#################### General settings ####################
# Device settings
use_gpu: True  # whether to use the gpu

# Inference simulation settings
sim_wall_time: 36  # unit: s. The simulation wall time. The simulation will stop if the wall time is reached.
sim_num: 2  # Number of simulations to run.

# Simulation metrics
save_collision_data_flag: True  # Save crash data. This must set to True if want to analyze crash type and crash severity.
gen_realistic_metric_flag: True  # Generate and save realistic metrics.
gen_realistic_metric_dict:  # What metrics to generate.
  PET: True  # Post-encroachment time.
  instant_speed: True  # Vehicle instantaneous speed
  yielding_speed_and_distance: True  # Each yielding moment calculate the yielding distance and speed with the conflicting vehicle.
  distance: True  # Vehicle distance

#################### Other settings ####################

# NeuralNDE model
# The parameters below are determined by your trained model
model: "transformer"
dataset: "ring"
history_length: 5  # number of historical steps input to the model
pred_length: 5  # number of predicted steps output by the model
m_tokens: 32  # maximum number of vehicles that can be handled by the model
# model_output: "position_xy"  # use traci.vehicle.moveToXY()
model_output: "position_dxdy"  # compute dx,dy, then use traci.vehicle.setSpeed()

# Checkpoints of the trained models (behavior modeling net, safety mapping net, etc.)
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_behavior_net_training_0.4_no_jump2/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_1/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_speed_acc/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_xy_out/checkpoints/last_ckpt.pt"
# behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_fixed_08-09-24/checkpoints/last_ckpt.pt"
behavior_model_ckpt_dir: "./results/training/behavior_net/ring_position_close_loop_8-20/checkpoints/last_ckpt.pt"
safety_mapper_ckpt_dir: "data/inference/rounD/safety_mapper_ckpt/safety_mapping_net.pt"

# Whether use neural safety mapping module
use_neural_safety_mapping: True

# Whether use conflict critic module (crash critic module)
use_conflict_critic_module: True

# Other inference simulation settings
sim_resol: 0.4  # simulation resolution. unit: s
rolling_step: 1  # How many pred steps to execute during autoregression.
interpolate_flag: False # Interpolate the trajectory to a finer time resolution for better visualization.
intep_steps: 3  # Number of steps to inter between steps. E.g., resolution is 0.4s intep_steps=3 then new resolution is 0.1s

# Simulation metrics dependencies
ROI_map_dir: "data/inference/ring/ROIs-map"  # Used for metric analysis.
PET_configs: # This is pixel coordinates of the basemap image
  width_start: 0
  width_end: 77
  width_n: 20
  width_res: 25.0
  height_start: 0
  height_end: 80
  height_n: 20
  height_res: 23.5
  # roundD drivable (936, 1678, 3)
  # width_start: 550
  # width_end: 1050
  # width_n: 20
  # width_res: 25.0
  # height_start: 230
  # height_end: 700
  # height_n: 20
  # height_res: 23.5

# Other save results and visualization
save_simulated_TIME_BUFF_flag: True  # Save all generated simulated trajectories
viz_flag: True  # Whether visualize the simulation.
save_viz_flag: True  # Save simulation visualizations
save_collision_data_flag: True
save_fps: 10

# Data needed for the simulation. E.g., map image, initial vehicle states, etc.
# basemap_dir: "data/inference/ring/basemap/ring-official-map.jpg"
# drivable_map_dir: &drivable_map_dir "data/inference/ring/drivablemap/ring-drivablemap.jpg"
# sim_remove_vehicle_area_map: "data/inference/ring/ROIs-map/ring-sim-remove-vehicle-area-map.jpg"  # E.g., exits.
# entrance_map_dir: &entrance_map_dir "data/inference/ring/ROIs-map/entrance"  # Only needed if want to use lane_based_safety_check for initialization.
# map_height: &map_height 400 #80  # The map height and width ratio should be consistent with the basemap and drivable map pictures.
# map_width: &map_width 400 #77
# init_traj_clips_dir: "data/inference/ring/simulation_initialization/initial_clips/"  # For initialization.
# traffic_generator_config:
#   method: Poisson  # Poisson or Random
#   gen_veh_states_dir: "data/inference/ring/simulation_initialization/gen_veh_states/ring/"  # The states of generated vehicle at entrance during the simulation
#   check_safety_method: uniform_safety_check  # lane_based_safety_check or uniform_safety_check
#   uniform_safety_buffer: 5
#   same_lane_safety_buffer: 8  # for lane based check
#   different_lane_safety_buffer: 5  # for lane based check
#   default_Poisson_arr_rate: 10000 #200
#   sim_resol: 0.4  # Should be consistent with Behavior modeling network output resolution
#   drivable_map_dir: *drivable_map_dir
#   map_height: *map_height
#   map_width: *map_width
#   entrance_map_dir: *entrance_map_dir


######### Training ##########
# # Training dataset
# dataset: "ring"
# path_to_traj_data: "data/training/behavior_net/ring/ring257"  # Trajectory data for training

# # Model settings
# model: transformer  # transformer or bn_mlp
# history_length: 5  # number of historical steps input to the model
# pred_length: 5  # number of predicted steps output by the model
# max_num_vehicles: 32  # maximum number of vehicles that can be handled by the model

# # Training settings
# batch_size: 32
# lr: 1.0e-4  # learning rate
# lr_decay_step_size: 300  # The number of training epochs to conduct lr decay. lr_scheduler.StepLR is used.
# lr_decay_gamma: 0.3  # lr_scheduler.StepLR is used.
# max_num_epochs: 2500  # maximum training epochs
# dataloader_num_workers: 8  # num_workers

# # Pre-trained safety mapping network
# # safety_mapper_ckpt_dir: "data/training/behavior_net/ring/safety_mapper_ckpt/safety_mapping_net.pt"
# safety_mapper_ckpt_dir: "data/inference/rounD/safety_mapper_ckpt/safety_mapping_net.pt"


########## sumo ##############
gui: True
sumocfg_file_name: "data/sumo/ring/circles.sumocfg"
max_steps: 100
step_length: 0.4
